#!/usr/bin/ruby

require "cgi"
cgi = CGI.new

puts "Cache-Control: no-cache"
puts "Content-type: text/html\n\n"

puts "<html>"
puts "<head>"
puts "<title>Hello, Ruby!</title>"
puts "</head>"
puts "<body>"

puts "<h1>Hello, Ruby!</h1>"
puts "<p>This do be generated by Ruby o-o.</p>"

dt_string = Time.now
puts "<p>Current Time: " + dt_string.strftime("%A %B %d %k:%M:%S %Y") + "</p>"

# IP Address is an environment variable when using CGI
address = cgi.remote_addr
puts "<p>Your IP Address: %s</p>" % [address]

puts "</body>"
puts "</html>"
