#!/usr/bin/ruby

require "cgi"
cgi = CGI.new

puts "Cache-Control: no-cache"
puts "Content-type: application/json\n\n"

dt_string = Time.now
address = cgi.remote_addr

puts "{"
puts "\t\"title\": \"Hello, Ruby!\","
puts "\t\"IP\": \"%s\"," % address
puts "\t\"time\": \"%s\"," % dt_string
puts "\t\"heading\": \"Hello, Ruby!\","
puts "\t\"message\": \"This do be generated by Ruby o-o.\""
puts "}"